package: searchit_search_api
version: '0.0.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/KLXM/searchit_search_api
requires:
    redaxo: '^5.18.1'
    php:
        version: '>=8.1, <9'
